### ISSUE TITLE
latest_nohealthcheck image is failing

### ISSUE THREAD

**Issue by visibilityspots** [mikenye/docker-adsbexchange#41]
when running the latest_nohealthcheck tag I got this error message

```
[adsbexchange-stats] /usr/local/bin/json-status: line 299: vcgencmd: command not found
```

tag 20201113_nohealthcheck is working fine

**Comment by mikenye** [comment]
Hi @visibilityspots,

This is due to this inclusion by the adsbx team: https://github.com/adsbxchange/adsbexchange-stats/blob/50035d990a6270be9edfea30655558d9c89fa1cb/json-status#L299

I've experimented with adding `vcgencmd` to the image, however without presenting the device `/dev/vchi` into the container, the `vcgencmd` command errors with:

```
VCHI initialization failed
```

My proposed solution is:

 * During image build, modify the adsbexchange-stats/json-status script with sed to change `STATUS=$(vcgencmd get_throttled)` to `STATUS=$(vcgencmd_get_throttled_wrapper.sh)`
 * Create `vcgencmd_get_throttled_wrapper.sh` that attempts to call `vcgencmd get_throttled`.
   * If the exit status of `vcgencmd` is not `0`, then spoof the output with `throttled=0x0`
   * If the command works (ie, user is on RPi and has forwarded the `/dev/vhci` into the container), then use that output.

What do you think?

**Comment by mikenye** [comment]
It looks like #42 has solved the problem.

**Comment by robbiet480** [comment]
See also https://github.com/mikenye/docker-adsbexchange/commit/842b85a6d4b77feb76d16cd2c08e72e2ac535e27
